/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    public static String subsequences(String word) {

        if(word.isEmpty()){
            return "";
        }
        else {
            char firstLetter = word.charAt(0);
            String restOfWord = word.substring(1);

            String subsequencesOfRest = subsequences(restOfWord);

            String result = "";
            for (String subsequence : subsequencesOfRest.split(",", -1)){
                result += "," + subsequence;
                result += "," + firstLetter + subsequence;
            }
            //wywalic przecinek
            result = result.substring(1);
            return result;
        }

    }

    public static String subsequnce(String word){
        return subsequencesAfter("",word);
    }

    private static String subsequencesAfter(String s, String word){
        if(word.isEmpty()){
            // base case
            return s;
        }
        else{
            //recursive step
            return  subsequencesAfter(s, word.substring(1)) +
                    "," +
                    subsequencesAfter(s+ word.charAt(0), word.substring(1));
        }
    }
}
